/*
 * Copyright © 2026 Matera Systems, Inc.
 * Licensed under the Matera Source License v1.0 (source-available; not open source). See LICENSE.md.
 * Creating a Derivative Work from this file — by AI/ML generation or by manual re-implementation
 * based on it — is governed by that license (see the "Derivative Work" definition and Annex A).
 */
package com.matera.x9qrcode.infrastructure.web.controller;

import com.matera.x9qrcode.infrastructure.AbstractIntegrationTest;

import com.nimbusds.jose.JOSEObjectType;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.JWSObject;
import com.nimbusds.jose.JWSSigner;
import com.nimbusds.jose.Payload;
import com.nimbusds.jose.crypto.ECDSASigner;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jose.util.Base64;
import com.nimbusds.jose.util.Base64URL;
import com.sun.net.httpserver.HttpServer;
import io.restassured.module.mockmvc.response.MockMvcResponse;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.test.context.TestPropertySource;

import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.security.MessageDigest;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.RSAPrivateKey;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import static io.restassured.module.mockmvc.RestAssuredMockMvc.given;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

/**
 * A payment notification signed by somebody who is <em>not us</em>.
 *
 * <p>Every other test in this suite mints its JWS by posting to our own
 * {@code /api/v1/signature/generate}: the service signs with the bundled demo key and then verifies
 * its own signature. That proves the JWS plumbing works, and almost nothing else. The demo key is
 * <b>self-signed</b>, and {@code JwsQRCodeSignatureService} deliberately skips revocation checking
 * for self-signed end entities — so the CA-issued branch, the one every real payer takes, was never
 * executed by a test at all.
 *
 * <p>Here the payer is a stranger holding a certificate issued by a CA, exactly as in production.
 * The fixtures are generated by {@code src/test/resources/certificate/generate-test-ca.sh} using
 * only {@code keytool}, committed so a fresh clone runs green with no setup, and named
 * {@code x9-test-*} with {@code Example} organisations so nobody mistakes them for real keys.
 *
 * <p>Two details make this work, and both were established by experiment rather than assumption:
 *
 * <ul>
 *   <li>The leaves carry a <b>CRL Distribution Point</b>. Without one PKIX refuses a CA-issued
 *       certificate outright with {@code UNDETERMINED_REVOCATION_STATUS} — {@code SOFT_FAIL} covers
 *       a revocation source being unreachable, not one being absent. A test without it would have
 *       passed or failed for reasons unrelated to what it claims to check.</li>
 *   <li>The CRL is served from a local HTTP server on {@link #CRL_PORT}. Nothing leaves the machine;
 *       the port is baked into the certificates at issuance, so it must match the generator.</li>
 * </ul>
 */
@TestPropertySource(properties = {
    "x9.certificate.truststore.location=classpath:/certificate/x9-test-truststore.jks",
    "x9.certificate.truststore.password=x9test123",
    "x9.certificate.truststore.alias=x9-test-ca"
})
class CaIssuedSignatureApiTest extends AbstractIntegrationTest {

    /** Must match CRL_PORT in generate-test-ca.sh — a distribution point is fixed at issuance. */
    private static final int CRL_PORT = 18081;

    private static final String CREATE = "/api/v1/payment-request";
    private static final String NOTIFY = "/pub/api/v1/payment-notification";
    private static final String APPLICATION_JOSE = "application/jose";
    private static final String STOREPASS = "x9test123";
    private static final long AMOUNT = 25_000L;

    private static HttpServer crlServer;

    @BeforeAll
    static void serveCrls() throws Exception {
        crlServer = HttpServer.create(new InetSocketAddress("127.0.0.1", CRL_PORT), 0);
        crlServer.createContext("/", exchange -> {
            String name = exchange.getRequestURI().getPath().replaceFirst("^/", "");

            try (InputStream crl = resource(name)) {
                byte[] bytes = crl.readAllBytes();
                exchange.getResponseHeaders().add("Content-Type", "application/pkix-crl");
                exchange.sendResponseHeaders(200, bytes.length);
                try (OutputStream out = exchange.getResponseBody()) {
                    out.write(bytes);
                }
            }
        });
        crlServer.start();
    }

    @AfterAll
    static void stopServingCrls() {
        if (crlServer != null) {
            crlServer.stop(0);
        }
    }

    private static InputStream resource(String name) {
        return CaIssuedSignatureApiTest.class.getResourceAsStream("/certificate/" + name);
    }

    // ------------------------------------------------------------------ signing as a third party

    /** A payer's keystore: its private key and the chain it will publish in {@code x5c}. */
    private record Payer(PrivateKey privateKey, List<X509Certificate> chain) {

        static Payer load(String keystore, String alias) throws Exception {
            KeyStore ks = KeyStore.getInstance("PKCS12");
            try (InputStream in = CaIssuedSignatureApiTest.class
                    .getResourceAsStream("/certificate/" + keystore)) {
                ks.load(in, STOREPASS.toCharArray());
            }

            List<X509Certificate> chain = new ArrayList<>();
            for (Certificate certificate : ks.getCertificateChain(alias)) {
                chain.add((X509Certificate) certificate);
            }

            return new Payer((PrivateKey) ks.getKey(alias, STOREPASS.toCharArray()), chain);
        }

        JWSAlgorithm algorithm() {
            return privateKey instanceof ECPrivateKey ? JWSAlgorithm.ES256 : JWSAlgorithm.PS512;
        }

        JWSSigner signer() throws Exception {
            return privateKey instanceof ECPrivateKey ec
                ? new ECDSASigner(ec)
                : new RSASSASigner((RSAPrivateKey) privateKey);
        }
    }

    /** {@code x5t#S256}: the SHA-256 digest of the leaf, which the service matches against x5c. */
    private static Base64URL sha256Thumbprint(X509Certificate leaf) throws Exception {
        return Base64URL.encode(MessageDigest.getInstance("SHA-256").digest(leaf.getEncoded()));
    }

    /**
     * The JWS a payer actually sends: its own chain in {@code x5c}, the thumbprint of its own leaf,
     * and the three critical headers X9.150 requires.
     */
    private String signAsPayer(Payer payer, String payload) throws Exception {
        List<Base64> x5c = payer.chain().stream()
                .map(certificate -> {
                    try {
                        return Base64.encode(certificate.getEncoded());
                    } catch (Exception e) {
                        throw new IllegalStateException(e);
                    }
                })
                .toList();

        Map<String, Object> critical = new LinkedHashMap<>();
        critical.put("correlationId", UUID.randomUUID().toString());
        critical.put("iat", Instant.now().toEpochMilli());
        critical.put("ttl", 300_000L);

        JWSHeader.Builder header = new JWSHeader.Builder(payer.algorithm())
                .type(JOSEObjectType.JOSE)
                .keyID("payer-key-1")
                .x509CertChain(x5c)
                .x509CertSHA256Thumbprint(sha256Thumbprint(payer.chain().getFirst()))
                .criticalParams(Set.of("correlationId", "iat", "ttl"));

        critical.forEach(header::customParam);

        JWSObject jws = new JWSObject(header.build(), new Payload(payload));
        jws.sign(payer.signer());

        return jws.serialize();
    }

    // --------------------------------------------------------------------------- the QR Code

    private String createQRCode() {
        String body = """
            {
              "validUntil": "2030-12-31T23:59:59Z",
              "creditor": {
                "name": "CA Issued Test", "phone": "+14155550100", "email": "test@example.com",
                "address": { "line1": "1 A St", "city": "Springfield", "state": "CA", "postalCode": "90001", "country": "US" },
                "MCC": "5999"
              },
              "bill": { "description": "ca issued", "amountDue": { "amount": %d, "currency": "USD" } },
              "paymentNotification": { "kind": "DEFAULT" },
              "paymentMethods": [
                { "currency": "USD", "validUntil": "2030-12-31T23:59:59Z", "amount": %d,
                  "networks": { "ach": { "routingNumber": "021000021", "accountNumber": "1234567890", "protectionType": "tokenized" } } }
              ]
            }
            """.formatted(AMOUNT, AMOUNT);

        return given().contentType("application/json").body(body)
                .when().post(CREATE)
                .then().statusCode(HttpStatus.CREATED.value())
                .extract().path("id");
    }

    private String notificationFor(String qrCodeId) {
        return """
            {
              "payment": { "qrcodeId": "%s", "amount": %d, "currency": "USD", "network": "ACH",
                           "transactionId": "021000021.0000001" },
              "payer": { "info": "Test Payer PSP" },
              "expectedDate": "2030-10-08T06:59:59Z"
            }
            """.formatted(qrCodeId, AMOUNT);
    }

    private MockMvcResponse notifyAs(Payer payer, String qrCodeId) throws Exception {
        return given().contentType(APPLICATION_JOSE)
                .body(signAsPayer(payer, notificationFor(qrCodeId)))
                .when().post(NOTIFY);
    }

    private String statusOf(String qrCodeId) {
        return given().when().get(CREATE + "/" + qrCodeId)
                .then().statusCode(HttpStatus.OK.value())
                .extract().path("status");
    }

    // ------------------------------------------------------------------------------- accepted

    @Test
    void anRsaPayerIssuedByATrustedCaIsAccepted() throws Exception {
        String qrCodeId = createQRCode();

        MockMvcResponse response = notifyAs(Payer.load("x9-test-payer.p12", "x9-test-payer"), qrCodeId);

        assertEquals(HttpStatus.OK.value(), response.statusCode(), response.asString());
        assertEquals("PAYMENT_INITIATED", statusOf(qrCodeId));
    }

    /**
     * The regression this file exists for.
     *
     * <p>{@code retrieveExternalJwkInformation} used to call {@code RSAKey.parse} unconditionally on
     * the {@code x5c} path, so an EC certificate was refused with "The public key of the X.509
     * certificate is not RSA" — while {@code createVerifier} held an {@code ECDSAVerifier} branch
     * that path could never reach.
     *
     * <p>The refused payer was the conformant one: X9.150 leaves {@code alg} to the X9-approved
     * suite rather than naming one, its own Annex A examples sign with {@code ES256}, and {@code x5c}
     * is an explicitly permitted way to carry the chain. Interoperability is the point of the
     * standard, so both key types must work.
     */
    @Test
    void anEcPayerIssuedByATrustedCaIsAccepted() throws Exception {
        String qrCodeId = createQRCode();

        MockMvcResponse response = notifyAs(Payer.load("x9-test-payer-ec.p12", "x9-test-payer-ec"), qrCodeId);

        assertEquals(HttpStatus.OK.value(), response.statusCode(),
                "an ES256 payer is conformant and must be accepted: " + response.asString());
        assertEquals("PAYMENT_INITIATED", statusOf(qrCodeId));
    }

    // ------------------------------------------------------------------------------- refused

    /**
     * ADR-0007's actual guarantee, which nothing tested before: the allowlist gates the certificate's
     * <b>issuer</b>. This payer's signature is perfectly valid — it is the issuer that is unknown.
     */
    @Test
    void aPayerFromAnUntrustedCaIsRefused() throws Exception {
        String qrCodeId = createQRCode();

        MockMvcResponse response =
            notifyAs(Payer.load("x9-test-untrusted-payer.p12", "x9-test-untrusted-payer"), qrCodeId);

        assertNotEquals(HttpStatus.OK.value(), response.statusCode(),
                "a validly-signed message from an unknown issuer must still be refused: " + response.asString());
        assertEquals("ACTIVE", statusOf(qrCodeId), "a refused notification must change nothing");
    }

    /**
     * Revocation is genuinely checked, not skipped. This leaf is issued by the trusted CA and signs
     * correctly; it appears on the CRL its own distribution point names, and that alone stops it.
     */
    @Test
    void aRevokedPayerIsRefused() throws Exception {
        String qrCodeId = createQRCode();

        MockMvcResponse response =
            notifyAs(Payer.load("x9-test-payer-revoked.p12", "x9-test-payer-revoked"), qrCodeId);

        assertNotEquals(HttpStatus.OK.value(), response.statusCode(),
                "a revoked certificate must be refused: " + response.asString());
        assertEquals("ACTIVE", statusOf(qrCodeId));
    }

}
