apiVersion: v1
kind: Secret
metadata:
  name: {{ include "x9-qrcode.fullname" . }}
  labels:
    {{- include "x9-qrcode.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.configEncryption.enabled }}
  jasypt.encryptor.password: {{ (required "The config 'secrets.configEncryption.password' is required! See documentation for more details!" .Values.secrets.configEncryption.password) | b64enc }}
  {{- end }}
  spring.data.mongodb.uri: {{ (required "The config 'secrets.spring.data.mongodb.uri' is required! See documentation for more details!" .Values.secrets.spring.data.mongodb.uri) | b64enc }}
  x9.certificate.privateKeystore.password: {{ (required "The config 'secrets.x9.certificate.privateKeystore.password' is required! See documentation for more details!" .Values.secrets.x9.certificate.privateKeystore.password) | b64enc }}
  x9.certificate.privateKeystore.privateKeyPassword: {{ (required "The config 'secrets.x9.certificate.privateKeystore.privateKeyPassword' is required! See documentation for more details!" .Values.secrets.x9.certificate.privateKeystore.privateKeyPassword) | b64enc }}
  x9.certificate.truststore.password: {{ (required "The config 'secrets.x9.certificate.truststore.password' is required! See documentation for more details!" .Values.secrets.x9.certificate.truststore.password) | b64enc }}
