#!/usr/bin/env bash
#
# Regenerates the CA-issued test PKI used by CaIssuedSignatureApiTest.
#
# NON-PRODUCTION. Every key here is committed to a public repository and is therefore public.
# Nothing generated by this script may ever be trusted outside the test suite.
#
# Why this exists at all: the shipped demo keystore is SELF-SIGNED, and JwsQRCodeSignatureService
# deliberately skips revocation checking for self-signed end-entity certificates. So the demo cert
# can never exercise the CA-issued branch — chain building, revocation, or the trusted-issuer
# allowlist. This PKI is the smallest thing that can.
#
# Needs `keytool` (ships with the JDK) and `bc` for one hex->decimal conversion. No openssl, no
# network, no real certificate, nothing downloaded.
#
#   ./generate-test-ca.sh
#
set -euo pipefail
cd "$(dirname "$0")"

STOREPASS="x9test123"
CRL_PORT="18081"                       # must match CaIssuedSignatureApiTest.CRL_PORT
CRL_URI="http://127.0.0.1:${CRL_PORT}/test-ca.crl"
# A SECOND distribution point, used only by the leaf we then revoke. Two URLs rather than one file
# swapped between tests: the JDK caches a fetched CRL, so reusing one URL would make the revocation
# test depend on execution order and on a cache TTL nobody controls.
CRL_URI_REVOKED="http://127.0.0.1:${CRL_PORT}/test-ca-revoked.crl"
DAYS_CA=7300                           # 20y: a fixture that expires is a test that breaks mysteriously
DAYS_LEAF=7300
DAYS_CRL=7300

rm -f x9-test-ca.p12 x9-test-payer.p12 x9-test-payer-ec.p12 x9-test-payer-revoked.p12 \
      x9-test-untrusted-ca.p12 x9-test-untrusted-payer.p12 x9-test-truststore.jks \
      test-ca.crl test-ca-revoked.crl ./*.cer ./*.csr ./*-chain.pem

say() { printf '\n== %s\n' "$1"; }

say "1/8  Test Root CA (the one we will trust AND allow)"
keytool -genkeypair -alias x9-test-ca -dname "CN=X9 QRCode Test Root CA,O=Matera Systems Test,C=US" \
  -keyalg RSA -keysize 3072 -sigalg SHA512withRSA -validity "$DAYS_CA" \
  -ext bc:c=ca:true,pathlen:0 -ext ku:c=keyCertSign,cRLSign \
  -keystore x9-test-ca.p12 -storetype PKCS12 -storepass "$STOREPASS" -keypass "$STOREPASS"

say "2/8  Untrusted Test CA (in NO truststore — proves an unknown issuer is refused)"
keytool -genkeypair -alias x9-test-untrusted-ca -dname "CN=Example Untrusted Test CA,O=Example Org,C=US" \
  -keyalg RSA -keysize 3072 -sigalg SHA512withRSA -validity "$DAYS_CA" \
  -ext bc:c=ca:true,pathlen:0 -ext ku:c=keyCertSign,cRLSign \
  -keystore x9-test-untrusted-ca.p12 -storetype PKCS12 -storepass "$STOREPASS" -keypass "$STOREPASS"

# issue <ca-store> <ca-alias> <leaf-store> <leaf-alias> <dn> [keyalg-args...]
#
# The CA is RSA and signs with SHA512withRSA regardless of the leaf's key type — an RSA CA issuing
# an EC leaf is ordinary. What changes is the leaf's own key, and therefore the JWS `alg` a payer
# holding it can use.
issue() {
  local CA_STORE="$1" CA_ALIAS="$2" LEAF_STORE="$3" LEAF_ALIAS="$4" DN="$5" CDP="$6"
  shift 6
  local KEY_ARGS=("$@")
  [ ${#KEY_ARGS[@]} -eq 0 ] && KEY_ARGS=(-keyalg RSA -keysize 3072 -sigalg SHA512withRSA)

  keytool -genkeypair -alias "$LEAF_ALIAS" -dname "$DN" \
    "${KEY_ARGS[@]}" -validity "$DAYS_LEAF" \
    -keystore "$LEAF_STORE" -storetype PKCS12 -storepass "$STOREPASS" -keypass "$STOREPASS"
  keytool -certreq -alias "$LEAF_ALIAS" -keystore "$LEAF_STORE" -storepass "$STOREPASS" -file "$LEAF_ALIAS.csr"
  # The CRL Distribution Point is what makes revocation DETERMINABLE. Without it PKIX rejects the
  # certificate outright with UNDETERMINED_REVOCATION_STATUS — SOFT_FAIL covers a revocation source
  # being unreachable, not one being absent. Verified, not assumed.
  keytool -gencert -alias "$CA_ALIAS" -keystore "$CA_STORE" -storepass "$STOREPASS" \
    -ext ku:c=digitalSignature,nonRepudiation -ext "crl=URI:${CDP}" \
    -validity "$DAYS_LEAF" -rfc -infile "$LEAF_ALIAS.csr" -outfile "$LEAF_ALIAS.cer"
  keytool -exportcert -alias "$CA_ALIAS" -keystore "$CA_STORE" -storepass "$STOREPASS" -rfc -file "$CA_ALIAS.cer"
  cat "$LEAF_ALIAS.cer" "$CA_ALIAS.cer" > "$LEAF_ALIAS-chain.pem"
  keytool -importcert -noprompt -alias "$CA_ALIAS" -file "$CA_ALIAS.cer" \
    -keystore "$LEAF_STORE" -storepass "$STOREPASS"
  keytool -importcert -noprompt -alias "$LEAF_ALIAS" -file "$LEAF_ALIAS-chain.pem" \
    -keystore "$LEAF_STORE" -storepass "$STOREPASS"
}

say "3/8  RSA payer leaf issued BY the Test Root CA (signs PS512)"
issue x9-test-ca.p12 x9-test-ca x9-test-payer.p12 x9-test-payer \
  "CN=Test Payer PSP,O=Example PSP,C=US" "$CRL_URI"

# ANSI X9.150-2026 leaves `alg` to the X9-approved suite (SD-34) and its own Annex A examples use
# ES256, so a conformant payer may well present an EC key. JwsQRCodeSignatureService reads `alg` from
# the JWS header and builds an ECDSAVerifier for ES256/384/512 — a branch nothing exercised before
# this fixture existed.
say "4/8  EC payer leaf issued BY the Test Root CA (signs ES256)"
issue x9-test-ca.p12 x9-test-ca x9-test-payer-ec.p12 x9-test-payer-ec \
  "CN=Test Payer PSP EC,O=Example PSP,C=US" "$CRL_URI" \
  -keyalg EC -groupname secp256r1 -sigalg SHA256withECDSA

say "5/8  Payer leaf that we will then REVOKE (its own distribution point)"
issue x9-test-ca.p12 x9-test-ca x9-test-payer-revoked.p12 x9-test-payer-revoked \
  "CN=Test Payer PSP Revoked,O=Example PSP,C=US" "$CRL_URI_REVOKED"

say "6/8  Payer leaf issued by the UNTRUSTED CA"
issue x9-test-untrusted-ca.p12 x9-test-untrusted-ca x9-test-untrusted-payer.p12 x9-test-untrusted-payer \
  "CN=Example Untrusted Payer,O=Example Org,C=US" "$CRL_URI"

say "7/8  Truststore holding ONLY the Test Root CA"
keytool -importcert -noprompt -alias x9-test-ca -file x9-test-ca.cer \
  -keystore x9-test-truststore.jks -storetype JKS -storepass "$STOREPASS"

say "8/8  Two CRLs: one revoking nothing, one revoking the RSA payer leaf"
keytool -gencrl -alias x9-test-ca -keystore x9-test-ca.p12 -storepass "$STOREPASS" \
  -validity "$DAYS_CRL" -file test-ca.crl
# keytool PRINTS a serial in hex but wants it in DECIMAL for -id. Convert with bc rather than shell
# arithmetic: a serial beginning 8-f exceeds signed 64-bit and would silently overflow.
SERIAL_HEX=$(keytool -printcert -file x9-test-payer-revoked.cer | awk -F': ' '/Serial number/{print $2; exit}')
SERIAL_DEC=$(echo "ibase=16; $(printf '%s' "$SERIAL_HEX" | tr 'a-f' 'A-F')" | bc)
keytool -gencrl -alias x9-test-ca -keystore x9-test-ca.p12 -storepass "$STOREPASS" \
  -id "${SERIAL_DEC}:1" -validity "$DAYS_CRL" -file test-ca-revoked.crl

# Keep only what the test loads: the two payer keystores, the truststore, and the two CRLs.
rm -f ./*.csr ./*-chain.pem ./*.cer
printf '\nDone. Revoked serial: %s (hex %s)\n' "$SERIAL_DEC" "$SERIAL_HEX"
ls -1
