<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.matera</groupId>
        <artifactId>x9-qrcode-parent</artifactId>
        <version>2.3.0-SNAPSHOT</version>
    </parent>

    <artifactId>x9-qrcode-build-init</artifactId>

    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <id>install-matera-emv-jar</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>mvn</executable>
                            <arguments>
                                <argument>install:install-file</argument>
                                <argument>-Dfile=${project.basedir}/../others/libs/emv-qrcode-0.1.3.jar</argument>
                                <argument>-DgroupId=com.matera.adopt</argument>
                                <argument>-DartifactId=emv-qrcode</argument>
                                <argument>-Dversion=0.1.3</argument>
                                <argument>-Dpackaging=jar</argument>
                                <argument>-q</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>